title: Blue Hackers Club
description: What can('t) we do together?
github:
    repository_url:
    owner_url: https://github.com/BlueHC
    owner_name: BlueHC
meetup: 
    url: https://www.meetup.com/Blue-Hackers-Club/
slack: 
    url: https://bluehc.slack.com
twitter: 
    url: https://twitter.com/BlueHCHamburg